import test from "node:test";
import assert from "node:assert/strict";
import { EventEmitter } from "node:events";
import { mkdtemp, mkdir, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { PassThrough } from "node:stream";
import { Controller } from "../src/controller.js";
import { Store } from "../src/store.js";
import { newRun, validateSpec } from "../src/state.js";
import { Effect, GitEffects } from "../src/effects.js";
import { guardPath } from "../src/path-policy.js";
import { WorkerAdapter, roleRoute } from "../src/worker.js";
const spec = (x = {}) => ({ taskKey: `t-${Math.random()}`, objective: "change", cwd: "/work", remote: "origin", base: "main", branch: "topic", paths: ["src"], checks: [["node", "--test"]], authorization: { edit: true, pr: true }, ...x });
class Effects { constructor(s) { this.spec = s; this.current = "h1"; this.calls = []; } async preflight() {} async head() { return this.current; } async prove(k) { return k === Effect.PUBLISH_PR ? { pr: "u" } : { head: this.current }; } async run(k) { this.calls.push(k); if (k === Effect.COMMIT) return { head: this.current }; if (k === Effect.REBASE) { this.current = "h2"; return { head: this.current }; } if (k === Effect.RECONCILE_PR) return { existing: null }; if (k === Effect.PUBLISH_PR) return { pr: "u" }; return { checked: 1 }; } }
function workers(dir) { const started=[]; const a = new WorkerAdapter({ stateDir: dir, spawnProcess: () => { const child = new EventEmitter(); Object.assign(child, { stdin:{write(){}}, stdout:new PassThrough(), stderr:new PassThrough() }); child.kill = () => child.emit("exit", 0, "SIGTERM"); return child; } }); const start=a.start.bind(a); a.start=(...x)=>{const w=start(...x);started.push(w);return w;}; a.bindAndPrompt=async()=>({success:true}); return {a,started}; }
const wait=async(f)=>{for(let i=0;i<100;i++){if(f())return;await new Promise(r=>setTimeout(r,2));}throw new Error("timeout");};
const report=(c,w,node,outcome)=>w.child.stdout.write(`${JSON.stringify({type:"tool_execution_end",toolName:"orchestrator_report",isError:false,result:{details:{node,generation:c.run.generation,token:w.token,role:w.role,outcome,summary:outcome}}})}\n`);

test("failed and blocked writer reports persist and stop before effects", async()=>{for(const outcome of ["failed","blocked"]){const d=await mkdtemp(join(tmpdir(),"o-"));const {a,started}=workers(d);const e=new Effects(spec());const c=new Controller({store:new Store(d),workers:a,effectsFor:()=>e,token:()=>"abcdefgh"});await c.start({workflow:"fix-to-pr",spec:spec()});await c.pump();report(c,started[0],"write",outcome);await wait(()=>c.run.status==="waiting-human");assert.equal(c.run.nodes.write.status,outcome);assert.equal(e.calls.length,0);await c.close();}});
test("ordered selector waits for running parallel sibling and completes read-only",async()=>{const d=await mkdtemp(join(tmpdir(),"p-"));const {a,started}=workers(d);const c=new Controller({store:new Store(d),workers:a,effectsFor:s=>new Effects(s),token:()=>"abcdefgh"});await c.start({workflow:"read-only-verify",spec:spec()});await c.pump();assert.equal(started.length,2);report(c,started[0],"verify-a","ok");await wait(()=>c.run.nodes["verify-a"]?.status==="ok");assert.equal(started.length,2);report(c,started[1],"verify-b","ok");await wait(()=>c.run.status==="done");await c.close();});
test("reconciliation decisions are specific and proven",async()=>{for(const decision of ["abandon","confirmed-not-applied"]){const d=await mkdtemp(join(tmpdir(),"r-"));const s=new Store(d);let run=await s.create(newRun({workflow:"fix-to-pr",spec:validateSpec(spec(),"fix-to-pr")}));run=await s.append(run,{id:"started",type:"effect-started",generation:run.generation,lease:run.lease,effect:"commit",kind:Effect.COMMIT});const c=new Controller({store:s,workers:workers(d).a,effectsFor:x=>new Effects(x)});await c.resume(run.id);await c.reconcile("commit",decision);assert.equal(c.run.status,decision==="abandon"?"failed":"running");await c.close();}});
test("path policy blocks escapes, symlinks and git but accepts scoped new file",async()=>{const root=await mkdtemp(join(tmpdir(),"path-"));await mkdir(join(root,"src"));await mkdir(join(root,".git"));const out=await mkdtemp(join(tmpdir(),"out-"));await symlink(out,join(root,"src","link"));const x={cwd:root,roots:[root],paths:["src"]};for(const p of ["../x","@/tmp/x","src/link/x",".git/config"])assert.throws(()=>guardPath({...x,input:p,write:true}));assert.equal(guardPath({...x,input:"src/new.js",write:true}),join(root,"src/new.js"));});
test("path policy preserves missing scoped suffixes",async()=>{const root=await mkdtemp(join(tmpdir(),"path-"));const out=await mkdtemp(join(tmpdir(),"out-"));await mkdir(join(root,"linked"));await symlink(out,join(root,"linked","escape"));const x={cwd:root,roots:[root],paths:["src"]};for(const input of ["src/value.txt","src/nested/value.txt"])assert.equal(guardPath({...x,input,write:true}),join(root,input));assert.throws(()=>guardPath({...x,input:"linked/escape/missing/value.txt",write:false}));});
test("preflight validates declared worktree branch remote and base",async()=>{const calls=[];const e=new GitEffects({spec:spec(),execFile:async(file,args)=>{calls.push([file,...args]);if(args[0]==="worktree")return{stdout:"worktree /work\n"};if(args[1]==="--show-toplevel")return{stdout:"/work\n"};if(args[1]==="--show-current")return{stdout:"topic\n"};if(args[0]==="status")return{stdout:""};return{stdout:"ok\n"};}});await e.preflight();assert.deepEqual(calls.map(x=>x.slice(1,3)),[["worktree","list"],["rev-parse","--show-toplevel"],["branch","--show-current"],["remote","get-url"],["rev-parse","--verify"],["status","--porcelain"]]);});
test("role routes are explicit",()=>{const a=new WorkerAdapter({stateDir:"/tmp/x",spawnProcess:()=>{throw new Error("no");}});for(const [role,r]of Object.entries(roleRoute)){const argv=a.argv({id:role,role});assert.equal(argv[argv.indexOf("--model")+1],`${r.provider}/${r.model}`);assert.equal(argv[argv.indexOf("--thinking")+1],r.thinking);}});
